# Generated by Django 3.2.16 on 2022-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ドリンク名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('src', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('hot_flag', models.BooleanField(default=False, verbose_name='温度フラグ')),
                ('soda_flag', models.BooleanField(default=False, verbose_name='炭酸フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
