# Generated by Django 3.2.16 on 2023-02-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='src',
            field=models.CharField(max_length=100, verbose_name='イメージ画像'),
        ),
    ]
